name: "Node Backend"
language: node_js
env:
    - NODE_ENV=CI
matrix:
    include:
        - name: Node 8
          node_js: "8"
        - name: Node 10
          node_js: "10"
        - name: Node 11
          node_js: "11"
install: npm i
script: npm test
cache:
    directories:
        - $HOME/node_modules
