name: expo
version: 0.0.1+2
description: A mobile app for voting on different HVL Expo exhibitions.
author:
homepage: hvl.no

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^0.5.0
  shared_preferences: ^0.5.1


  # firebase dependencies
  firebase_ml_vision: ^0.6.0+1
  firebase_auth: ^0.8.1+3
  firebase_analytics: ^2.0.2+1

  # other packages
  meta: ^1.1.6
  equatable: ^0.2.0
  http: ^0.12.0+1
  date_format: ^1.0.6
  local_auth: ^0.4.0+1
  uuid: ^2.0.0

  # widgets
  liquid_pull_to_refresh: ^1.1.0
  side_header_list_view: ^0.0.4
  auto_size_text: ^1.0.0
  cached_network_image: ^0.7.0

  # qr related
  qr_mobile_vision: ^0.2.2
  qr: ^1.0.1
  
  # redux packages
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  redux_epics: ^0.10.4
  redux_logging: ^0.3.0

  # built value types
  built_value: ^6.3.2
  built_collection: ^4.1.0

  # memoizing
  memoize: ^2.0.0


  # scripts dependencies
  args: ^1.5.1
  image: ^2.0.7

  # theme
  groovin_material_icons: ^1.1.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/hvl_logo.png
    - assets/images/expo-transparent.png
    - assets/images/firebase.png

  fonts:
    - family: Akademie
      fonts:
        - asset: assets/fonts/Akademie-Std-Light.otf
          weight: 300 #300l/400r/500m/600b
        - asset: assets/fonts/Akademie-Std.otf
          weight: 400
        - asset: assets/fonts/Akademie-Std-Medium.otf
          weight: 500
        - asset: assets/fonts/Akademie-Std-Bold.otf
          weight: 600
        - asset: assets/fonts/Akademie-Std-Black.otf
          weight: 700


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
